### ISSUE TITLE
Web App issues: yarn build

### ISSUE THREAD

**Issue by awjohn** [gvolpe/trading#150]
[nixos@DESKTOP-NTIRA6H:/mnt/c/Users/awjoh/NixOS2/trading/modules/ws-client]$ yarn build
yarn run v1.22.17
warning package.json: No license field
$ parcel build index.html --dist-dir dist --log-level info
🚨 Build failed.

@parcel/core: Failed to resolve './target/scala-3.1.1/webapp-fastopt.js' from './tyrianapp.js'

  /mnt/c/Users/awjoh/NixOS2/trading/modules/ws-client/tyrianapp.js:3:8
    2 |   TyrianApp
  > 3 | } from './target/scala-3.1.1/webapp-fastopt.js';
  >   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    4 |
    5 | TyrianApp.launch("trading-ws");

@parcel/resolver-default: Cannot load file './target/scala-3.1.1/webapp-fastopt.js' in './'.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gvolpe** [comment]
Are you using the given `flake.nix` for the environment, or how did you install `yarn`?

**Comment by gvolpe** [comment]
Aaaah I think the README misses the instruction to build the `Scala.js` app, try `sbt webapp/fastOptJS` first. I'll give it a try tomorrow from scratch to verify whether that's it or there's something else missing.

**Comment by gvolpe** [comment]
Fixed in https://github.com/gvolpe/trading/commit/2bbf7a50fe9f07173c204644b4c669deb851439f, let me know if it works now. I'll need to find a way to keep that version up to date whenever the Scala version is updated.

**Comment by awjohn** [comment]
Yes, webapp/fastOptJS did the trick! Then updated tyrianapp.js to use scala-3.2.0-RC3 instead of scala-3.1.1
