### ISSUE TITLE
Upgrading dependencies causes smokey to fail

### ISSUE THREAD

**Issue by paul-snively** [gvolpe/trading#285]
I've forked this project. My fork can be found [here](https://github.com/paul-snively/trading).

I've tried to limit myself to upgrading the Scala 3 version to the LTS version, and upgrading the core dependencies to their latest versions supporting Scala 3. In terms of source code changes, this has been completely trivial.

However, when I stand everything up and run `sbt smoke`, the test fails due to a websocket connection timing out, and several of the expected messages not being received.

Doing the same with the original code passes using the same JVM on the same host.

Looking at the evolving dependencies, my biggest concern is the changes to the http4s JDK client used for websocket support. It appears to have undergone significant revision from M6 to M7, revolving around new cats-effect capabilities. However, neither reverting to M6 (the last version in which `simple` returns a `Resource`) and M3 (the version used in the original code) solves the problem. Nevertheless, the finicky-looking nature of the websocket client with respect to state and lifecycles continues to make me nervous.

Any suggestions would be greatly appreciated.

**Comment by gvolpe** [comment]
Hi @paul-snively 👋🏽 

I'll have a look, that looks a lot like a bug in `http4s`. I had pending upgrading all dependencies anyway #289

**Comment by paul-snively** [comment]
I download the patch for #289 and applied it to my fork of your `main` branch, and sure enough, the smoke tests now pass.

Do you have some information about what the bug was, and where/how it was resolved?

Thanks so much!

**Comment by gvolpe** [comment]
@paul-snively I haven't upgraded `http4s` yet, so that's more likely where the bug resides. I'll have to investigate further...

**Comment by gvolpe** [comment]
@paul-snively looks like #290 [fixed it](https://github.com/gvolpe/trading/actions/runs/6066503946). Let me know if that works for you.

**Comment by paul-snively** [comment]
Yep, patch applies cleanly on top of #289 applied to `main`, and `sbt smoke` passes.

Thanks so much!
